export enum DDMetric {
  // Ncanto Related Metrics
  NcantoBatchCompleted = 'interactions.batch.completed',
  NcantoBatchSize = 'interactions.batch_size',
  NcantoBlacklistAssetFailure = 'ncanto.blacklist.asset.failure',
  NcantoBlacklistAssetSuccess = 'ncanto.blacklist.asset.success',
  NcantoCreateProfileFailure = 'ncanto.create.profile.failure',
  NcantoCreateProfileSuccess = 'ncanto.create.profile.success',
  NcantoCreateStoreFailure = 'ncanto.create.store.failure',
  NcantoCreateStoreSuccess = 'ncanto.create.store.success',
  NcantoEventsMissingContent = 'ncanto.events.missing.content',
  NcantoFailureInteractions = 'interactions.processed.failure',
  NcantoGetPanelRecommendationsFailure = 'ncanto.get.panel_recommendations.failure',
  NcantoGetPanelRecommendationsSuccess = 'ncanto.get.panel_recommendations.success',
  NcantoGetProfileFailure = 'ncanto.get.profile.failure',
  NcantoGetProfileSuccess = 'ncanto.get.profile.success',
  NcantoGetRecommendationsFailure = 'ncanto.get.recommendations.failure',
  NcantoGetRecommendationsSuccess = 'ncanto.get.recommendations.success',
  NcantoGetStoreFailure = 'ncanto.get.store.failure',
  NcantoGetStoreSuccess = 'ncanto.get.store.success',
  NcantoGetSubscriberFailure = 'ncanto.get.subscriber.failure',
  NcantoGetSubscriberSuccess = 'ncanto.get.subscriber.success',
  NcantoProfileAddFailure = 'ncanto.add.profile.failure',
  NcantoProfileAddSuccess = 'ncanto.add.profile.success',
  NcantoRecommendationRowEmpty = 'ncanto.recommendation.row.empty',
  NcantoRemoveContentMetadataFailure = 'ncanto.remove.content.metadata.failure',
  NcantoRemoveContentMetadataSuccess = 'ncanto.remove.content.metadata.success',
  NcantoRowRate = 'ncanto.row_rate',
  NcantoStoreAssetUpdateFailure = 'ncanto.update.asset.failure',
  NcantoStoreAssetUpdateSuccess = 'ncanto.update.asset.success',
  NcantoSubscriberCreationFailure = 'ncanto.create.subscriber.failure',
  NcantoSubscriberCreationSuccess = 'ncanto.create.subscriber.success',
  NcantoSuccessInteractions = 'interactions.processed.success',
  NcantoSuccessRate = 'interactions.success_rate',
  NcantoTotalDroppedInteractions = 'interactions.dropped.total',
  NcantoTotalProcessedInteractions = 'interactions.processed.total',
  NcantoTotalSuccessInteractions = 'interactions.success.total',
  NcantoUpdateSubscriberFailure = 'ncanto.update.subscriber.failure',
  NcantoUpdateSubscriberSuccess = 'ncanto.update.subscriber.success',

  // Recommendation Related Metrics
  RecommendationPlatterEmpty = 'recommendation.platter.empty',
  RecommendationPlatterFallbackEmpty = 'recommendation.platter.fallback.empty',
  RecommendationRowCacheEmpty = 'recommendation.row.cache.empty',
  RecommendationRowEmpty = 'recommendation.row.empty',
  RecommendationRowFallbackEmpty = 'recommendation.row.fallback.empty',
  RecommendationRowRate = 'recommendation.row_rate',
}
