import { Document } from 'mongoose';

import { Dialect, Lang } from '@app/common/enums/app.enum';
import { EpisodeStatus } from 'common/entities/episode.entity';
import { Episode, EpisodeType } from 'src/content/entities/episodes.entity';
import { Peripheral } from 'src/content/schemas/peripheral.schema';
export const episodeData: Omit<Episode, Exclude<keyof Document, '_id'>>[] = [
  {
    _id: 17,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
          },
        },
        id: 1,
        square: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'Oj4gZKzBaYBgVvqiGipw.jpeg',
          },
        },
      },
    ],
    artistList: [
      {
        callingName: 'Ramnath',
        city: 'Karnal',
        display: 'Ramnath Shastry',
        firstName: 'Ramnath',
        gender: 'male',
        gradient: '#93552e',
        id: 101,
        lastName: 'Shastry',
        name: 'Ramnath Shastry',
        order: 1,
        profilePic: 'XxIihPE7OCbJhYOUTjxS.jpeg',
        slug: 'ramnath-shastri',
        status: 'active',
      },
    ],
    caption: '',
    categoryList: [{ id: 1, name: 'Sample Category' }],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: '',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date(),
    deepLink: 'https://share.stage.in/HinB',
    description:
      'Yahan kavi ne btaya hai ki ek kanya ki aatma kaise bhagwan se rote hue baat karti hai ki usko janam dene se pehle hi maar diya gaya aur wo duniya dekhne se kis terah vanchit reh gayi.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 419,
    endDate: new Date('2020-07-17T07:37:05.423Z'),
    englishValidated: false,
    episodeOrder: 5,
    feedRandomOrder: 0,
    freeEpisode: false,
    freeEpisodeDuration: 600,
    genre: 'Poetry',
    genreList: [
      { id: 1, name: 'Action' },
      { id: 2, name: 'Comedy' },
      { id: 3, name: 'Drama' },
    ],
    hindiValidated: false,
    hlsSourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.m3u8',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: false,
    isPopularContent: false,
    isPremium: true,
    keywordSearch: '',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: [],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 289,
    parentDetail: {
      seasonTitle: 'Season -1',
      slug: 'choriyaan-bojh-na-hoti',
      sourceLink: 'showImage-1594971313892.jpg',
      title: 'Choriyan Bojh Na Hoti',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: 159,
    releaseDate: new Date(),
    seasonId: 17,
    seasonSlug: 'season-1',
    selectedPeripheral: new Peripheral(),
    showId: 7,
    showSlug: 'choriyaan-bojh-na-hoti',
    skipDisclaimer: false,
    slug: 'aatma-kanya-ki',
    sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
    startDate: new Date('2020-07-17T07:37:05.423Z'),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'Choriyan Bojh Na Hoti, Ramnath Shastri, Dayal Chand',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#92542e',
          sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
        },
      },
    },
    title: 'Aatma Kanya Ki',
    type: EpisodeType.Season,
    updatedAt: new Date('2024-08-02T01:59:59.186Z'),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 799,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: ['20230113142834459326952619c430ee'],
    visionularHlsHistory: ['20221230103439619116285e1d775e79'],
  },
  {
    _id: 171,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
          },
        },
        id: 1,
        square: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'Oj4gZKzBaYBgVvqiGipw.jpeg',
          },
        },
      },
    ],
    artistList: [
      {
        callingName: 'Ramnath',
        city: 'Karnal',
        display: 'Ramnath Shastry',
        firstName: 'Ramnath',
        gender: 'male',
        gradient: '#93552e',
        id: 101,
        lastName: 'Shastry',
        name: 'Ramnath Shastry',
        order: 1,
        profilePic: 'XxIihPE7OCbJhYOUTjxS.jpeg',
        slug: 'ramnath-shastri',
        status: 'active',
      },
    ],
    caption: '',
    categoryList: [{ id: 1, name: 'Sample Category 170' }],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: '',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date(),
    deepLink: 'https://share.stage.in/HinB',
    description:
      '170 Yahan kavi ne btaya hai ki ek kanya ki aatma kaise bhagwan se rote hue baat karti hai ki usko janam dene se pehle hi maar diya gaya aur wo duniya dekhne se kis terah vanchit reh gayi.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 4190,
    endDate: new Date('2020-07-17T07:37:05.423Z'),
    englishValidated: false,
    episodeOrder: 1,
    feedRandomOrder: 0,
    freeEpisode: false,
    freeEpisodeDuration: 600,
    genre: 'Poetry',
    genreList: [
      { id: 1, name: 'Action' },
      { id: 2, name: 'Comedy' },
      { id: 3, name: 'Drama' },
    ],
    hindiValidated: false,
    hlsSourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.m3u8',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: false,
    isPopularContent: false,
    isPremium: true,
    keywordSearch: '',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: [],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 289,
    parentDetail: {
      seasonTitle: 'Season -1',
      slug: 'choriyaan-bojh-na-hoti',
      sourceLink: 'showImage-1594971313892.jpg',
      title: 'Choriyan Bojh Na Hoti',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: 159,
    releaseDate: new Date(),
    seasonId: 17,
    seasonSlug: 'season-1',
    selectedPeripheral: new Peripheral(),
    showId: 7,
    showSlug: 'choriyaan-bojh-na-hoti',
    skipDisclaimer: false,
    slug: 'new-khani',
    sourceLink: 'new-kahani-knya-ki-ajsdkjsakhdjh234234.mp4',
    startDate: new Date('2020-07-17T07:37:05.423Z'),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'New Kahani Bojh Na Hoti, Ramnath Shastri, Dayal Chand',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#92542e',
          sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
        },
      },
    },
    title: 'New Kanya Ki',
    type: EpisodeType.Movie,
    updatedAt: new Date('2024-08-02T01:59:59.186Z'),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 799,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: ['20230113142834459326952619c430ee'],
    visionularHlsHistory: ['20221230103439619116285e1d775e79'],
  },
  {
    _id: 170,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
          },
        },
        id: 1,
        square: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'Oj4gZKzBaYBgVvqiGipw.jpeg',
          },
        },
      },
    ],
    artistList: [
      {
        callingName: 'Ramnath',
        city: 'Karnal',
        display: 'Ramnath Shastry',
        firstName: 'Ramnath',
        gender: 'male',
        gradient: '#93552e',
        id: 101,
        lastName: 'Shastry',
        name: 'Ramnath Shastry',
        order: 1,
        profilePic: 'XxIihPE7OCbJhYOUTjxS.jpeg',
        slug: 'ramnath-shastri',
        status: 'active',
      },
    ],
    caption: '',
    categoryList: [{ id: 1, name: 'Sample Category 170' }],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: '',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description:
      '170 Yahan kavi ne btaya hai ki ek kanya ki aatma kaise bhagwan se rote hue baat karti hai ki usko janam dene se pehle hi maar diya gaya aur wo duniya dekhne se kis terah vanchit reh gayi.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 4190,
    endDate: new Date('2020-07-17T07:37:05.423Z'),
    englishValidated: false,
    episodeOrder: 1,
    feedRandomOrder: 0,
    freeEpisode: false,
    freeEpisodeDuration: 600,
    genre: 'Poetry',
    genreList: [
      { id: 1, name: 'Action' },
      { id: 2, name: 'Comedy' },
      { id: 3, name: 'Drama' },
    ],
    hindiValidated: false,
    hlsSourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.m3u8',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: false,
    isPopularContent: false,
    isPremium: true,
    keywordSearch: '',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: [],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 289,
    parentDetail: {
      seasonTitle: 'Season -1',
      slug: 'choriyaan-bojh-na-hoti',
      sourceLink: 'showImage-1594971313892.jpg',
      title: 'Choriyan Bojh Na Hoti',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: 159,
    releaseDate: new Date(),
    seasonId: 17,
    seasonSlug: 'season-1',
    selectedPeripheral: new Peripheral(),
    showId: 7,
    showSlug: 'choriyaan-bojh-na-hoti',
    skipDisclaimer: false,
    slug: 'new-khani',
    sourceLink: 'new-kahani-knya-ki-ajsdkjsakhdjh234234.mp4',
    startDate: new Date('2020-07-17T07:37:05.423Z'),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'New Kahani Bojh Na Hoti, Ramnath Shastri, Dayal Chand',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#92542e',
          sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
        },
      },
    },
    title: 'New Kanya Ki',
    type: EpisodeType.Movie,
    updatedAt: new Date('2024-08-02T01:59:59.186Z'),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 799,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: ['20230113142834459326952619c430ee'],
    visionularHlsHistory: ['20221230103439619116285e1d775e79'],
  },
  {
    _id: 2,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#4a90e2',
            sourceLink: 'sample_individual_episode_thumbnail.jpg',
          },
        },
        id: 1,
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: 'PG',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-05T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description: 'This is a sample individual episode.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 1800, // 30 minutes in seconds
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    englishValidated: true,
    episodeOrder: 1,
    feedRandomOrder: 1,
    freeEpisode: true,
    freeEpisodeDuration: 300, // 5 minutes preview in seconds
    genre: 'Drama',
    genreList: [{ id: 2, name: 'Poetry' }],
    hindiValidated: false,
    hlsSourceLink: 'https://example.com/sample-individual-episode/hls',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: true,
    isPopularContent: false,
    isPremium: false,
    keywordSearch: 'sample individual episode drama',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: ['sample', 'individual', 'episode'],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: 'Season 1',
      slug: 'sample-show',
      sourceLink: 'sample_show_thumbnail.jpg',
      title: 'Sample Show',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: Math.floor(Math.random() * 1000),
    releaseDate: new Date(),
    seasonId: 1,
    seasonSlug: '',
    selectedPeripheral: {
      duration: 0,
      hlsSourceLink: 'Movie peripheral',
      sourceLink: 'Movie peripheral',
      thumbnail: {
        horizontal: { sourceLink: 'Movie peripheral' },
        square: { sourceLink: 'Movie peripheral' },
        tv_image: { sourceLink: 'Movie peripheral' },
        vertical: { sourceLink: 'Movie peripheral' },
      },
      title: 'Movie peripheral',
      type: 'Movie peripheral',
      viewCount: 0,
      visionularHls: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
      visionularHlsH265: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
    },
    showId: 1,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'sample-individual-episode',
    sourceLink: 'https://example.com/sample-individual-episode',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'sample,individual,episode',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#4a90e2',
          sourceLink: 'sample_individual_episode_thumbnail.jpg',
        },
      },
    },
    title: 'This is movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 0,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
  {
    _id: 2412,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#4a90e2',
            sourceLink: 'sample_individual_episode_thumbnail.jpg',
          },
        },
        id: 1,
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: 'PG',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-03T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description: 'This is a sample individual episode.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 1800, // 30 minutes in seconds
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    englishValidated: true,
    episodeOrder: 1,
    feedRandomOrder: 1,
    freeEpisode: true,
    freeEpisodeDuration: 300, // 5 minutes preview in seconds
    genre: 'Drama',
    genreList: [{ id: 2, name: 'Poetry' }],
    hindiValidated: false,
    hlsSourceLink: 'https://example.com/sample-individual-episode/hls',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: true,
    isPopularContent: false,
    isPremium: false,
    keywordSearch: 'sample individual episode drama',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: ['sample', 'individual', 'episode'],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: 'Season 1',
      slug: 'sample-show',
      sourceLink: 'sample_show_thumbnail.jpg',
      title: 'Sample Show',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: Math.floor(Math.random() * 1000),
    releaseDate: new Date(),
    seasonId: 1,
    seasonSlug: '',
    selectedPeripheral: {
      duration: 0,
      hlsSourceLink: 'Movie peripheral',
      sourceLink: 'Movie peripheral',
      thumbnail: {
        horizontal: { sourceLink: 'Movie peripheral' },
        square: { sourceLink: 'Movie peripheral' },
        tv_image: { sourceLink: 'Movie peripheral' },
        vertical: { sourceLink: 'Movie peripheral' },
      },
      title: 'Movie peripheral',
      type: 'Movie peripheral',
      viewCount: 0,
      visionularHls: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
      visionularHlsH265: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
    },
    showId: 1,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'sample-individual-episode-3',
    sourceLink: 'https://example.com/sample-individual-episode',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'sample,individual,episode',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#4a90e2',
          sourceLink: 'sample_individual_episode_thumbnail.jpg',
        },
      },
    },
    title: 'This is movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 0,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
  {
    _id: 2413,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#4a90e2',
            sourceLink: 'sample_individual_episode_thumbnail.jpg',
          },
        },
        id: 1,
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: 'PG',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-02T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description: 'This is a sample individual episode.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 1800, // 30 minutes in seconds
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    englishValidated: true,
    episodeOrder: 1,
    feedRandomOrder: 1,
    freeEpisode: true,
    freeEpisodeDuration: 300, // 5 minutes preview in seconds
    genre: 'Drama',
    genreList: [{ id: 2, name: 'Poetry' }],
    hindiValidated: false,
    hlsSourceLink: 'https://example.com/sample-individual-episode/hls',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: true,
    isPopularContent: false,
    isPremium: false,
    keywordSearch: 'sample individual episode drama',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: ['sample', 'individual', 'episode'],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: 'Season 1',
      slug: 'sample-show',
      sourceLink: 'sample_show_thumbnail.jpg',
      title: 'Sample Show',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: Math.floor(Math.random() * 1000),
    releaseDate: new Date(),
    seasonId: 1,
    seasonSlug: '',
    selectedPeripheral: {
      duration: 0,
      hlsSourceLink: 'Movie peripheral',
      sourceLink: 'Movie peripheral',
      thumbnail: {
        horizontal: { sourceLink: 'Movie peripheral' },
        square: { sourceLink: 'Movie peripheral' },
        tv_image: { sourceLink: 'Movie peripheral' },
        vertical: { sourceLink: 'Movie peripheral' },
      },
      title: 'Movie peripheral',
      type: 'Movie peripheral',
      viewCount: 0,
      visionularHls: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
      visionularHlsH265: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
    },
    showId: 1,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'sample-individual-episode-4',
    sourceLink: 'https://example.com/sample-individual-episode',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'sample,individual,episode',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#4a90e2',
          sourceLink: 'sample_individual_episode_thumbnail.jpg',
        },
      },
    },
    title: 'This is movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 0,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
  {
    _id: 2410,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#4a90e2',
            sourceLink: 'sample_individual_episode_thumbnail.jpg',
          },
        },
        id: 1,
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: 'PG',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-01T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description: 'This is a sample individual episode.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 1800, // 30 minutes in seconds
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    englishValidated: true,
    episodeOrder: 1,
    feedRandomOrder: 1,
    freeEpisode: true,
    freeEpisodeDuration: 300, // 5 minutes preview in seconds
    genre: 'Drama',
    genreList: [{ id: 2, name: 'Poetry' }],
    hindiValidated: false,
    hlsSourceLink: 'https://example.com/sample-individual-episode/hls',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: true,
    isPopularContent: false,
    isPremium: false,
    keywordSearch: 'sample individual episode drama',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: ['sample', 'individual', 'episode'],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: 'Season 1',
      slug: 'sample-show',
      sourceLink: 'sample_show_thumbnail.jpg',
      title: 'Sample Show',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: Math.floor(Math.random() * 1000),
    releaseDate: new Date(),
    seasonId: 1,
    seasonSlug: '',
    selectedPeripheral: {
      duration: 0,
      hlsSourceLink: 'Movie peripheral',
      sourceLink: 'Movie peripheral',
      thumbnail: {
        horizontal: { sourceLink: 'Movie peripheral' },
        square: { sourceLink: 'Movie peripheral' },
        tv_image: { sourceLink: 'Movie peripheral' },
        vertical: { sourceLink: 'Movie peripheral' },
      },
      title: 'Movie peripheral',
      type: 'Movie peripheral',
      viewCount: 0,
      visionularHls: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
      visionularHlsH265: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
    },
    showId: 1,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'sample-individual-episode-1',
    sourceLink: 'https://example.com/sample-individual-episode',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'sample,individual,episode',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#4a90e2',
          sourceLink: 'sample_individual_episode_thumbnail.jpg',
        },
      },
    },
    title: 'This is movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 0,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
  {
    _id: 2411,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#4a90e2',
            sourceLink: 'sample_individual_episode_thumbnail.jpg',
          },
        },
        id: 1,
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: 'PG',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date('2024-01-02T00:00:00.000Z'),
    deepLink: 'https://share.example.com/SampleIndividualEpisode',
    description: 'This is a sample individual episode.',
    descriptorTags: [],
    displayLanguage: Lang.EN,
    duration: 1800, // 30 minutes in seconds
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    englishValidated: true,
    episodeOrder: 1,
    feedRandomOrder: 1,
    freeEpisode: true,
    freeEpisodeDuration: 300, // 5 minutes preview in seconds
    genre: 'Drama',
    genreList: [{ id: 2, name: 'Poetry' }],
    hindiValidated: false,
    hlsSourceLink: 'https://example.com/sample-individual-episode/hls',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: true,
    isPopularContent: false,
    isPremium: false,
    keywordSearch: 'sample individual episode drama',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Aatma Kanya Ki',
    metaKeyword: 'Aatma Kanya Ki',
    metaTags: ['sample', 'individual', 'episode'],
    metaTitle: 'Aatma Kanya Ki',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: 'Season 1',
      slug: 'sample-show',
      sourceLink: 'sample_show_thumbnail.jpg',
      title: 'Sample Show',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: Math.floor(Math.random() * 1000),
    releaseDate: new Date(),
    seasonId: 1,
    seasonSlug: '',
    selectedPeripheral: {
      duration: 0,
      hlsSourceLink: 'Movie peripheral',
      sourceLink: 'Movie peripheral',
      thumbnail: {
        horizontal: { sourceLink: 'Movie peripheral' },
        square: { sourceLink: 'Movie peripheral' },
        tv_image: { sourceLink: 'Movie peripheral' },
        vertical: { sourceLink: 'Movie peripheral' },
      },
      title: 'Movie peripheral',
      type: 'Movie peripheral',
      viewCount: 0,
      visionularHls: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
      visionularHlsH265: {
        hlsSourcelink: 'Movie peripheral',
        sourceLink: 'Movie peripheral',
        status: 'Movie peripheral',
        visionularTaskId: 'Movie peripheral',
      },
    },
    showId: 1,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'sample-individual-episode-2',
    sourceLink: 'https://example.com/sample-individual-episode',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [
      { id: 27, name: 'vibhatsa-ras' },
      { id: 26, name: 'roudra-ras' },
      { id: 24, name: 'karuna-ras' },
      { id: 25, name: 'adbhut-ras' },
    ],
    tags: 'sample,individual,episode',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#4a90e2',
          sourceLink: 'sample_individual_episode_thumbnail.jpg',
        },
      },
    },
    title: 'This is movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
      { bitRate: 480, label: '480px', size: 23.22 },
      { bitRate: 360, label: '360px', size: 15.96 },
      { bitRate: 240, label: '240px', size: 11.28 },
    ],
    videoSize: 0,
    viewCount: 0,
    visionularHls: {
      hlsSourcelink: 'aatma-kanya-ki_1672396478806/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20221230103439619116285e1d775e79',
    },
    visionularHlsH265: {
      hlsSourcelink: 'aatma-kanya-ki_1673620113090/playlist.m3u8',
      sourceLink: 'aatma-knya-ki-ajsdkjsakhdjh234234.mp4',
      status: 'succeeded',
      visionularTaskId: '20230113142834459326952619c430ee',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
  // Movie with Hindi display language for reel tests
  {
    _id: 1711,
    adsTime: [],
    allThumbnails: [
      {
        horizontal: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
          },
        },
        id: 1,
        square: {
          ratio1: {
            gradient: '#92542e',
            sourceLink: 'Oj4gZKzBaYBgVvqiGipw.jpeg',
          },
        },
      },
    ],
    artistList: [],
    caption: '',
    categoryList: [{ id: 1, name: 'Sample Category' }],
    clips: { audioClip: '', videoClip: '' },
    collectionId: 0,
    collectionSlug: '',
    comingSoonDate: new Date(),
    complianceList: [],
    complianceRating: '',
    consumptionRateCount: 0,
    contentWarnings: [],
    contributionField: '',
    createdAt: new Date(),
    deepLink: 'https://share.stage.in/HinB',
    description: 'Hindi movie for reel testing',
    descriptorTags: [],
    displayLanguage: Lang.HIN,
    duration: 4190,
    endDate: new Date('2020-07-17T07:37:05.423Z'),
    englishValidated: false,
    episodeOrder: 1,
    feedRandomOrder: 0,
    freeEpisode: false,
    freeEpisodeDuration: 600,
    genre: 'Drama',
    genreList: [
      { id: 1, name: 'Action' },
      { id: 2, name: 'Comedy' },
      { id: 3, name: 'Drama' },
    ],
    hindiValidated: true,
    hlsSourceLink: 'test-hindi-movie.m3u8',
    introEndTime: 0,
    introStartTime: 0,
    isComingSoon: 0,
    isExclusive: 0,
    isExclusiveOrder: 0,
    isNewContent: false,
    isPopularContent: false,
    isPremium: true,
    keywordSearch: '',
    label: '',
    language: Dialect.HAR,
    like: 0,
    likeConsumptionRatio: 0,
    likeCount: 0,
    location: '',
    metaDescription: 'Hindi Movie',
    metaKeyword: 'Hindi Movie',
    metaTags: [],
    metaTitle: 'Hindi Movie',
    mood: '',
    moods: [],
    nextEpisodeNudgeStartTime: 0,
    order: 1,
    parentDetail: {
      seasonTitle: '',
      slug: '',
      sourceLink: '',
      title: '',
    },
    preContentWarningText: '',
    premiumNessOrder: 0,
    publishCount: 1,
    randomOrder: 1,
    releaseDate: new Date(),
    seasonId: 0,
    seasonSlug: '',
    selectedPeripheral: new Peripheral(),
    showId: 0,
    showSlug: '',
    skipDisclaimer: false,
    slug: 'hindi-movie-for-reels',
    sourceLink: 'test-hindi-movie.mp4',
    startDate: new Date(),
    status: EpisodeStatus.ACTIVE,
    subGenreList: [],
    tags: 'Hindi, Movie, Test',
    tg: '',
    theme: '',
    themes: [],
    thumbnail: {
      horizontal: {
        ratio1: {
          gradient: '#92542e',
          sourceLink: 'W0oSq5idQfz70gtohlCH.jpeg',
        },
      },
    },
    title: 'Hindi Movie',
    type: EpisodeType.Movie,
    updatedAt: new Date(),
    videoFormatDetail: [
      { bitRate: 1080, label: '1080px', size: 43.17 },
      { bitRate: 720, label: '720px', size: 32.99 },
    ],
    videoSize: 0,
    viewCount: 100,
    visionularHls: {
      hlsSourcelink: 'test-hindi-movie/playlist.m3u8',
      sourceLink: 'test-hindi-movie.mp4',
      status: 'succeeded',
      visionularTaskId: 'test123',
    },
    visionularHlsH265: {
      hlsSourcelink: 'test-hindi-movie-h265/playlist.m3u8',
      sourceLink: 'test-hindi-movie.mp4',
      status: 'succeeded',
      visionularTaskId: 'test456',
    },
    visionularHlsH265History: [],
    visionularHlsHistory: [],
  },
];

export const allMoviesData: Omit<Episode, Exclude<keyof Document, '_id'>>[] = [
  {
    ...episodeData[1],
    _id: 1,
    displayLanguage: Lang.EN,
    slug: 'slug-1',
    status: EpisodeStatus.ACTIVE,
    title: 'DJ Marwar',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 20,
    displayLanguage: Lang.HIN,
    slug: 'slug-1',
    status: EpisodeStatus.ACTIVE,
    title: 'DJ मारवाड़',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 3,
    displayLanguage: Lang.EN,
    slug: 'slug-2',
    status: EpisodeStatus.ACTIVE,
    title: 'Mehandipur Balaji',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 4,
    displayLanguage: Lang.HIN,
    slug: 'slug-2',
    status: EpisodeStatus.ACTIVE,
    title: 'मेहंदीपुर बालाजी',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 5,
    displayLanguage: Lang.EN,
    slug: 'slug-3',
    status: EpisodeStatus.ACTIVE,
    title: 'JAI HIND',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 6,
    displayLanguage: Lang.HIN,
    slug: 'slug-3',
    status: EpisodeStatus.ACTIVE,
    title: 'जय हिन्द',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 7,
    displayLanguage: Lang.EN,
    slug: 'slug-4',
    status: EpisodeStatus.ACTIVE,
    title: 'BHAWANI',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 8,
    displayLanguage: Lang.HIN,
    slug: 'slug-4',
    status: EpisodeStatus.ACTIVE,
    title: 'भवानी',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 9,
    displayLanguage: Lang.EN,
    slug: 'slug-5',
    status: EpisodeStatus.ACTIVE,
    title: 'Sarkari Bateu',
    type: EpisodeType.Movie,
  },
  {
    ...episodeData[1],
    _id: 10,
    displayLanguage: Lang.HIN,
    slug: 'slug-5',
    status: EpisodeStatus.ACTIVE,
    title: 'सरकारी बटेऊसरकारी बटेऊ',
    type: EpisodeType.Movie,
  },
];
