import { Document, Types } from 'mongoose';

import {
  CurrencyEnum,
  CurrencySymbolEnum,
  Lang,
  OS,
} from '@app/common/enums/app.enum';
import { PaywallItemTypeEnum } from 'common/entities/paywall.entity';
import { DayCountEnum, Plan } from 'common/entities/plan.entity';
import { PlanCountryEnum, PlanTypesEnum } from 'src/payment/enums/plan.enum';
import { PlanStatusEnum } from 'src/payment/enums/plan.enum';

export const plans: (Omit<Plan, keyof Document> & { _id: Types.ObjectId })[] = [
  {
    _id: new Types.ObjectId(),
    actualPrice: 199,
    cardOptionen: [
      'Unlimited Downloads',
      'Make your favourite list',
      'New web - series + films + Comedy shows',
    ],
    cardOptionhin: [
      'अनलिमिटेड डाउनलोड्स',
      'अपनी पसंदीदा लिस्ट बनाये',
      'नए वेब सीरीज + फिल्म + कॉमेडी शो',
    ],
    country: PlanCountryEnum.IN,
    createdAt: new Date('2024-09-23T07:38:12.709Z'),
    currency: CurrencyEnum.INR,
    currencySymbol: CurrencySymbolEnum.INR,
    dayCount: DayCountEnum.TRIAL,
    discount: 0,
    isRecommended: false,
    isRecurring: true,
    isTrailPlan: true,
    itemId: 'trial_quarter_07_lang_hing',
    mandateSetupPayingPrice: 199,
    mediaAssets: {
      [Lang.EN]: {
        buttonItem: {
          backgroundColor: '',
          color: '',
          fontSize: 0,
          fontWeight: 0,
          isEnabled: true,
          label: '',
          order: 0,
          outlineColor: '',
          textColor: '',
          type: PaywallItemTypeEnum.BUTTON,
        },
        footerText: '',
        paywallAssets: [
          {
            aspectRatio: '',
            backgroundColor: '',
            isEnabled: true,
            order: 0,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_IMAGE,
          },
          {
            aspectRatio: '',
            autoplay: true,
            isEnabled: true,
            loop: true,
            muted: true,
            order: 1,
            showControls: true,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_VIDEO,
          },
        ],
        renewalImage: '',
        subscriptionImage: '',
      },
      [Lang.HIN]: {
        buttonItem: {
          backgroundColor: '',
          color: '',
          fontSize: 0,
          fontWeight: 0,
          isEnabled: true,
          label: '',
          order: 0,
          outlineColor: '',
          textColor: '',
          type: PaywallItemTypeEnum.BUTTON,
        },
        footerText: '',
        paywallAssets: [
          {
            aspectRatio: '',
            backgroundColor: '',
            isEnabled: true,
            order: 0,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_IMAGE,
          },
          {
            aspectRatio: '',
            autoplay: true,
            isEnabled: true,
            loop: true,
            muted: true,
            order: 1,
            showControls: true,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_VIDEO,
          },
        ],
        renewalImage: '',
        subscriptionImage: '',
      },
    },
    offerTextEn: '50% off on 12 Months pack',
    offerTextHin: '12 महीने क पैक पर 50% की छूट!',
    os: OS.ANDROID,
    payingPrice: 1,
    paywallId: '',
    planDays: '7 days',
    planId: 'trial_quarter_07_lang_hing',
    planPartOfABTestGroup: ['A', 'B'],
    planTagsEn: '',
    planTagsHin: '',
    planType: PlanTypesEnum.MONTHLY,
    planTypeHin: '7 दिनों के लिए',
    planTypeMode: 'Trial',
    planTypeText: '7 Days Plan',
    planTypeTextHin: '7 दिनों के लिए',
    postTrialPlan: 'quarterly_149',
    priority: 0,
    saved: 7,
    status: PlanStatusEnum.ACTIVE,
    subscriptionDate: new Date('2024-09-23T07:38:12.709Z'),
    subscriptionValid: new Date('2024-09-23T07:38:12.709Z'),
    totalCount: 5,
    totalDays: 10,
    updatedAt: new Date('2024-09-23T07:38:12.709Z'),
  },
  {
    _id: new Types.ObjectId(),
    actualPrice: 149,
    cardOptionen: [
      'Unlimited Downloads',
      'Make your favourite list',
      'New web - series + films + Comedy shows',
    ],
    cardOptionhin: [
      'अनलिमिटेड डाउनलोड्स',
      'अपनी पसंदीदा लिस्ट बनाये',
      'नए वेब सीरीज + फिल्म + कॉमेडी शो',
    ],
    country: PlanCountryEnum.IN,
    createdAt: new Date('2024-09-23T07:38:12.709Z'),
    currency: CurrencyEnum.INR,
    currencySymbol: CurrencySymbolEnum.INR,
    dayCount: DayCountEnum.DEFAULT,
    discount: 0,
    isRecommended: false,
    isRecurring: true,
    isTrailPlan: false,
    itemId: 'quarterly_149',
    mandateSetupPayingPrice: 149,
    mediaAssets: {
      [Lang.EN]: {
        buttonItem: {
          backgroundColor: '',
          color: '',
          fontSize: 0,
          fontWeight: 0,
          isEnabled: true,
          label: '',
          order: 0,
          outlineColor: '',
          textColor: '',
          type: PaywallItemTypeEnum.BUTTON,
        },
        footerText: '',
        paywallAssets: [
          {
            aspectRatio: '',
            backgroundColor: '',
            isEnabled: true,
            order: 0,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_IMAGE,
          },
          {
            aspectRatio: '',
            autoplay: true,
            isEnabled: true,
            loop: true,
            muted: true,
            order: 1,
            showControls: true,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_VIDEO,
          },
        ],
        renewalImage: '',
        subscriptionImage: '',
      },
      [Lang.HIN]: {
        buttonItem: {
          backgroundColor: '',
          color: '',
          fontSize: 0,
          fontWeight: 0,
          isEnabled: true,
          label: '',
          order: 0,
          outlineColor: '',
          textColor: '',
          type: PaywallItemTypeEnum.BUTTON,
        },
        footerText: '',
        paywallAssets: [
          {
            aspectRatio: '',
            backgroundColor: '',
            isEnabled: true,
            order: 0,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_IMAGE,
          },
          {
            aspectRatio: '',
            autoplay: true,
            isEnabled: true,
            loop: true,
            muted: true,
            order: 1,
            showControls: true,
            sourceLink: '',
            type: PaywallItemTypeEnum.MEDIA_VIDEO,
          },
        ],
        renewalImage: '',
        subscriptionImage: '',
      },
    },
    offerTextEn: '50% off on 12 Months pack',
    offerTextHin: '12 महीने क पैक पर 50% की छूट!',
    os: OS.ANDROID,
    payingPrice: 149,
    paywallId: '',
    planDays: '7 days',
    planId: 'quarterly_149',
    planPartOfABTestGroup: ['A', 'B'],
    planTagsEn: '',
    planTagsHin: '',
    planType: PlanTypesEnum.QUARTERLY,
    planTypeHin: '7 दिनों के लिए',
    planTypeMode: 'Trial',
    planTypeText: '7 Days Plan',
    planTypeTextHin: '7 दिनों के लिए',
    postTrialPlan: '',
    priority: 0,
    saved: 7,
    status: PlanStatusEnum.ACTIVE,
    subscriptionDate: new Date('2024-09-23T07:38:12.709Z'),
    subscriptionValid: new Date('2024-09-23T07:38:12.709Z'),
    totalCount: 5,
    totalDays: 10,
    updatedAt: new Date('2024-09-23T07:38:12.709Z'),
  },
];
