import { Document, Types } from 'mongoose';

import { NotificationStatusEnum, User } from '@app/common/entities/user.entity';
import { Dialect, OS, Platform } from '@app/common/enums/app.enum';

export const userData: Omit<User, Exclude<keyof Document, '_id'>>[] = [
  {
    _id: new Types.ObjectId('5f7c6b5e1c9d440000a1b1a1'),
    appOpenCount: 10,
    appOpenDatesArr: [new Date('2023-01-01'), new Date('2023-01-02')],
    appVersion: '1.0.0',
    artistResumedList: { 'artist-1': 120, 'artist-2': 240 },
    artistseen: { 'artist-3': 150, 'artist-4': 300 },
    categoryPreference: [1, 2, 3],
    collectionMediaResumedList: { 'collection-1': 300, 'collection-2': 450 },
    consumedGenre: { 'genre-1': 500, 'genre-2': 750 },
    continueWatchingList: [
      {
        entitySlug: 'show-3',
        episodeSeasonSlug: 'season-2',
        episodeSlug: 'episode-5',
        lapsedPercentage: 75,
        lapseTime: 1500,
        showSlug: 'show-3',
      },
    ],
    countryCode: '+91',
    createdAt: new Date('2023-01-01'),
    currentCity: 'New York',
    currentClientIP: '192.168.1.2',
    currentCountry: 'USA',
    currentState: 'NY',
    dayCount: 5,
    deviceId: 'device-123456',
    episodeResumedList: { 'episode-1': 600, 'episode-2': 900 },
    generatedOTPCount: 3,
    genres: ['comedy', 'drama'],
    individualEpisodeResumedList: {
      'episode-4': 1200,
      'sample-individual-episode': 750,
    },
    initialUserCulture: Dialect.HAR,
    installedDate: new Date('2023-01-01'),
    isflutterUser: true,
    isLoggedIn: true,
    isNewUser: false,
    isTNPLUser: false,
    language: 'en',
    lapseTime: 300,
    lastSeenDetail: [
      {
        episodeSlug: 'episode-1',
        seasonSlug: 'season-1',
        showId: 1,
        showSlug: 'show-1',
      },
    ],
    locationHistory: [
      {
        City: 'New York',
        ClientIP: '192.168.1.2',
        Country: 'USA',
        State: 'NY',
        Timestamp: new Date('2023-01-01'),
      },
    ],
    loginType: 'mobilenumber',
    notificationStatus: NotificationStatusEnum.ACTIVE,
    onboarding: true,
    onboardingConsumption: true,
    onboardingShow: true,
    onboardingVideoStatus: true,
    otp: 123456,
    primaryLanguage: Dialect.HAR,
    primaryMobileNumber: '1234567890',
    relatedContent: { 'content-1': 100, 'content-2': 200 },
    showMediaResumedList: { 'show-1': 1800, 'show-2': 2400 },
    signUpBuildNumber: '505831',
    signUpOs: OS.ANDROID,
    signUpPlatform: Platform.APP,
    status: 'active',
    type: 'regular',
    uninstalledStatus: false,
    updatedAt: new Date('2023-01-02'),
    userCulture: Dialect.HAR,
    userIP: '192.168.1.1',
    userName: 'TestUser',
    userType: 'regular',
  },
  {
    _id: new Types.ObjectId('683e7aefb77a945b8a29e85f'),
    appOpenCount: 10,
    appOpenDatesArr: [new Date('2023-01-01'), new Date('2023-01-02')],
    appVersion: '1.0.0',
    artistResumedList: { 'artist-1': 120, 'artist-2': 240 },
    artistseen: { 'artist-3': 150, 'artist-4': 300 },
    categoryPreference: [1, 2, 3],
    collectionMediaResumedList: { 'collection-1': 300, 'collection-2': 450 },
    consumedGenre: { 'genre-1': 500, 'genre-2': 750 },
    continueWatchingList: [
      {
        entitySlug: 'show-3',
        episodeSeasonSlug: 'season-2',
        episodeSlug: 'episode-5',
        lapsedPercentage: 75,
        lapseTime: 1500,
        showSlug: 'show-3',
      },
    ],
    countryCode: '+91',
    createdAt: new Date('2023-01-01'),
    currentCity: 'New York',
    currentClientIP: '192.168.1.2',
    currentCountry: 'USA',
    currentState: 'NY',
    dayCount: 5,
    deviceId: 'device-654321',
    episodeResumedList: { 'episode-1': 600, 'episode-2': 900 },
    generatedOTPCount: 3,
    genres: ['comedy', 'drama'],
    individualEpisodeResumedList: {
      'episode-4': 1200,
      'sample-individual-episode': 750,
    },
    initialUserCulture: Dialect.HAR,
    installedDate: new Date('2023-01-01'),
    isflutterUser: true,
    isLoggedIn: true,
    isNewUser: false,
    isTNPLUser: false,
    language: 'en',
    lapseTime: 300,
    lastSeenDetail: [
      {
        episodeSlug: 'episode-1',
        seasonSlug: 'season-1',
        showId: 1,
        showSlug: 'show-1',
      },
    ],
    locationHistory: [
      {
        City: 'New York',
        ClientIP: '192.168.1.2',
        Country: 'USA',
        State: 'NY',
        Timestamp: new Date('2023-01-01'),
      },
    ],
    loginType: 'mobilenumber',
    notificationStatus: NotificationStatusEnum.ACTIVE,
    onboarding: true,
    onboardingConsumption: true,
    onboardingShow: true,
    onboardingVideoStatus: true,
    otp: 123456,
    primaryLanguage: Dialect.HAR,
    primaryMobileNumber: '1234567890',
    relatedContent: { 'content-1': 100, 'content-2': 200 },
    showMediaResumedList: { 'show-1': 1800, 'show-2': 2400 },
    status: 'active',
    type: 'regular',
    uninstalledStatus: false,
    updatedAt: new Date('2023-01-02'),
    userCulture: Dialect.HAR,
    userIP: '192.168.1.1',
    userName: 'TestUser',
    userType: 'regular',
  },
  {
    _id: new Types.ObjectId('683ed4119618be9a38e3a8c9'),
    appOpenCount: 10,
    appOpenDatesArr: [new Date('2023-01-01'), new Date('2023-01-02')],
    appVersion: '1.0.0',
    artistResumedList: { 'artist-1': 120, 'artist-2': 240 },
    artistseen: { 'artist-3': 150, 'artist-4': 300 },
    categoryPreference: [1, 2, 3],
    collectionMediaResumedList: { 'collection-1': 300, 'collection-2': 450 },
    consumedGenre: { 'genre-1': 500, 'genre-2': 750 },
    continueWatchingList: [
      {
        entitySlug: 'show-3',
        episodeSeasonSlug: 'season-2',
        episodeSlug: 'episode-5',
        lapsedPercentage: 75,
        lapseTime: 1500,
        showSlug: 'show-3',
      },
    ],
    countryCode: '+91',
    createdAt: new Date('2023-01-01'),
    currentCity: 'New York',
    currentClientIP: '192.168.1.2',
    currentCountry: 'USA',
    currentState: 'NY',
    dayCount: 5,
    deviceId: 'device-123456',
    episodeResumedList: { 'episode-1': 600, 'episode-2': 900 },
    generatedOTPCount: 3,
    genres: ['comedy', 'drama'],
    individualEpisodeResumedList: {
      'episode-4': 1200,
      'sample-individual-episode': 750,
    },
    initialUserCulture: Dialect.HAR,
    installedDate: new Date('2023-01-01'),
    isflutterUser: true,
    isLoggedIn: true,
    isNewUser: false,
    isTNPLUser: false,
    language: 'en',
    lapseTime: 300,
    lastSeenDetail: [
      {
        episodeSlug: 'episode-1',
        seasonSlug: 'season-1',
        showId: 1,
        showSlug: 'show-1',
      },
    ],
    locationHistory: [
      {
        City: 'New York',
        ClientIP: '192.168.1.2',
        Country: 'USA',
        State: 'NY',
        Timestamp: new Date('2023-01-01'),
      },
    ],
    loginType: 'mobilenumber',
    notificationStatus: NotificationStatusEnum.ACTIVE,
    onboarding: true,
    onboardingConsumption: true,
    onboardingShow: true,
    onboardingVideoStatus: true,
    otp: 123456,
    primaryLanguage: Dialect.HAR,
    primaryMobileNumber: '1234567890',
    relatedContent: { 'content-1': 100, 'content-2': 200 },
    showMediaResumedList: { 'show-1': 1800, 'show-2': 2400 },
    status: 'active',
    type: 'regular',
    uninstalledStatus: false,
    updatedAt: new Date('2023-01-02'),
    userCulture: Dialect.HAR,
    userIP: '192.168.1.1',
    userName: 'TestUser',
    userType: 'regular',
  },
  {
    _id: new Types.ObjectId('683ed3efa4acba353e3fd792'),
    appOpenCount: 10,
    appOpenDatesArr: [new Date('2023-01-01'), new Date('2023-01-02')],
    appVersion: '1.0.0',
    artistResumedList: { 'artist-1': 120, 'artist-2': 240 },
    artistseen: { 'artist-3': 150, 'artist-4': 300 },
    categoryPreference: [1, 2, 3],
    collectionMediaResumedList: { 'collection-1': 300, 'collection-2': 450 },
    consumedGenre: { 'genre-1': 500, 'genre-2': 750 },
    continueWatchingList: [
      {
        entitySlug: 'show-3',
        episodeSeasonSlug: 'season-2',
        episodeSlug: 'episode-5',
        lapsedPercentage: 75,
        lapseTime: 1500,
        showSlug: 'show-3',
      },
    ],
    countryCode: '+91',
    createdAt: new Date('2023-01-01'),
    currentCity: 'New York',
    currentClientIP: '192.168.1.2',
    currentCountry: 'USA',
    currentState: 'NY',
    dayCount: 5,
    deviceId: 'device-123456',
    episodeResumedList: { 'episode-1': 600, 'episode-2': 900 },
    generatedOTPCount: 3,
    genres: ['comedy', 'drama'],
    individualEpisodeResumedList: {
      'episode-4': 1200,
      'sample-individual-episode': 750,
    },
    initialUserCulture: Dialect.HAR,
    installedDate: new Date('2023-01-01'),
    isflutterUser: true,
    isLoggedIn: true,
    isNewUser: false,
    isTNPLUser: false,
    language: 'en',
    lapseTime: 300,
    lastSeenDetail: [
      {
        episodeSlug: 'episode-1',
        seasonSlug: 'season-1',
        showId: 1,
        showSlug: 'show-1',
      },
    ],
    locationHistory: [
      {
        City: 'New York',
        ClientIP: '192.168.1.2',
        Country: 'USA',
        State: 'NY',
        Timestamp: new Date('2023-01-01'),
      },
    ],
    loginType: 'mobilenumber',
    notificationStatus: NotificationStatusEnum.ACTIVE,
    onboarding: true,
    onboardingConsumption: true,
    onboardingShow: true,
    onboardingVideoStatus: true,
    otp: 123456,
    primaryLanguage: Dialect.HAR,
    primaryMobileNumber: '1234567890',
    relatedContent: { 'content-1': 100, 'content-2': 200 },
    showMediaResumedList: { 'show-1': 1800, 'show-2': 2400 },
    status: 'active',
    type: 'regular',
    uninstalledStatus: false,
    updatedAt: new Date('2023-01-02'),
    userCulture: Dialect.HAR,
    userIP: '192.168.1.1',
    userName: 'TestUser',
    userType: 'regular',
  },
  // User specifically for account invite tests (index 4)
  {
    _id: new Types.ObjectId('695b67720f4efa54ca7b7c50'),
    appOpenCount: 5,
    appOpenDatesArr: [new Date('2023-02-01')],
    appVersion: '1.0.0',
    artistResumedList: {},
    artistseen: {},
    categoryPreference: [],
    collectionMediaResumedList: {},
    consumedGenre: {},
    continueWatchingList: [],
    countryCode: '+91',
    createdAt: new Date('2023-02-01'),
    currentCity: 'Mumbai',
    currentClientIP: '192.168.1.10',
    currentCountry: 'India',
    currentState: 'MH',
    dayCount: 1,
    deviceId: 'device-account-invite',
    episodeResumedList: {},
    generatedOTPCount: 1,
    genres: [],
    individualEpisodeResumedList: {},
    initialUserCulture: Dialect.HAR,
    installedDate: new Date('2023-02-01'),
    isflutterUser: true,
    isLoggedIn: true,
    isNewUser: false,
    isTNPLUser: false,
    language: 'en',
    lapseTime: 0,
    lastSeenDetail: [],
    locationHistory: [],
    loginType: 'mobilenumber',
    notificationStatus: NotificationStatusEnum.ACTIVE,
    onboarding: true,
    onboardingConsumption: true,
    onboardingShow: true,
    onboardingVideoStatus: true,
    otp: 654321,
    primaryLanguage: Dialect.HAR,
    primaryMobileNumber: '9876543210',
    relatedContent: {},
    showMediaResumedList: {},
    status: 'active',
    type: 'regular',
    uninstalledStatus: false,
    updatedAt: new Date('2023-02-02'),
    userCulture: Dialect.HAR,
    userIP: '192.168.1.10',
    userName: 'AccountInviteUser',
    userType: 'regular',
  },
];
