export enum TrailerStatusEnum {
  IDLE = "idle",
  PROCESSING = "processing",
  COMPLETED = "completed",
  FAILED = "failed",
  // Python processing status values
  PROCESSING_INITIATED = "processing-initiated",
  PROCESSING_PROGRESS = "processing-progress",
  PROCESSING_COMPLETE = "processing-complete",
  PROCESSING_FAILED = "processing-failed",
  INITIATED = "initiated",
  DOWNLOADING = "downloading",
  PROGRESS = "progress",
  COMPLETE = "complete",
  // Python granular status values
  PARSING_INPUTS = "parsing_inputs",
  DETECTING_SCENES = "detecting_scenes",
  ANALYZING_AUDIO = "analyzing_audio",
  ANALYZING_VISUAL = "analyzing_visual",
  UNDERSTANDING_CONTENT = "understanding_content",
  GENERATING_NARRATIVES = "generating_narratives",
  ASSEMBLING_TRAILERS = "assembling_trailers",
  UPLOADING = "uploading",
}

// Terminal states where polling should stop
export const TERMINAL_STATUSES = [
  TrailerStatusEnum.COMPLETED,
  TrailerStatusEnum.FAILED,
  TrailerStatusEnum.IDLE,
  TrailerStatusEnum.PROCESSING_COMPLETE,
  TrailerStatusEnum.PROCESSING_FAILED,
  TrailerStatusEnum.COMPLETE,
];

export enum TrailerStatusTypeEnum {
  CREATED = "created",
  ANALYZING = "analyzing",
  GENERATING = "generating",
  RENDERING = "rendering",
  FINALIZING = "finalizing",
  COMPLETED = "completed",
  FAILED = "failed",
}

export enum TrailerUploadStatusEnum {
  IDLE = "idle",
  UPLOADING = "uploading",
  UPLOAD_COMPLETED = "upload-completed",
  UPLOAD_FAILED = "upload-failed",
}

export interface TrailerContentMetadata {
  title?: string;
  genre?: string;
  language?: string;
  targetDuration?: number;
}

export interface TrailerRecommendations {
  bestAutoGenerated?: string;
  bestForMarketing?: string;
  bestForSocialMedia?: string;
  editorNotes?: string;
  mostUnique?: string;
}

// Shot sequence item in variant metadata
export interface ShotSequenceItem {
  order: number;
  scene_ref?: string;
  timecode_start?: string;
  timecode_end?: string;
  recommended_duration?: number;
  purpose?: string;
  audio_recommendation?: string;
  dialogue_line?: string | null;
  transition_in?: string;
  is_hook_ending?: boolean;
}

// Variant structure metadata
export interface VariantStructure {
  phases?: string[];
  hook_strength?: number;
  cliffhanger?: string;
  description?: string;
}

// Full variant metadata from narrative JSON
export interface VariantMetadata {
  actual_duration?: number;
  target_duration?: number;
  structure?: VariantStructure;
  shot_sequence?: ShotSequenceItem[];
  music_recommendation?: {
    style?: string;
    has_dialogue_gaps?: boolean;
  };
  text_overlays?: Array<{
    text?: string;
    phase?: string;
    timing?: number;
  }>;
  opening_hook?: string;
  closing_tag?: string;
  suspense_peak?: number;
  character_intro_present?: boolean;
  hook_ending_present?: boolean;
  production_ready?: boolean;
}

export interface TrailerVariant {
  id: string;
  style: string;
  title?: string;
  duration?: number;
  confidence?: number;
  fileSize?: number;
  hookEnding?: string;
  s3Key: string;
  signedUrl?: string;
  metadata?: VariantMetadata;
}

export interface TrailerProjectListItem {
  _id: string;
  projectId: string;
  rawMediaId?: string;
  contentSlug?: string;
  contentMetadata?: TrailerContentMetadata;
  sourceLink?: string;
  startedAt?: Date;
  completedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface TrailerProjectDetail extends TrailerProjectListItem {
  editorGuideUrl?: string;
  error?: string;
  narrativeJsonUrl?: string;
  recommendations?: TrailerRecommendations;
  variants: TrailerVariant[];
}

export interface TrailerStatusResponse {
  projectId: string;
  rawMediaId: string;
  status: TrailerStatusEnum;
  statusType: TrailerStatusTypeEnum;
  progress: number;
  error?: string;
}

export interface PaginatedResponseDTO<T> {
  data: T[];
  nextPageAvailable: boolean;
  page: number;
  perPage: number;
}

export type GetTrailerListResponse = PaginatedResponseDTO<TrailerProjectListItem>;

export interface CreateTrailerProjectRequest {
  projectId: string;
  rawMediaId?: string;
  contentSlug?: string;
  contentMetadata?: TrailerContentMetadata;
}

export interface CreateTrailerProjectResponse {
  projectId: string;
  rawMediaId?: string;
  contentSlug?: string;
  contentMetadata?: TrailerContentMetadata;
  startedAt?: Date;
}

export interface GenerateTrailerRequest {
  rawMediaId: string;
  projectId?: string;
  narrativeStyles?: string[];
  targetDuration?: number;
  contentMetadata?: TrailerContentMetadata;
}

export interface GenerateTrailerResponse {
  projectId: string;
  rawMediaId: string;
  status: TrailerStatusEnum;
  statusType: TrailerStatusTypeEnum;
  message: string;
}

export interface TrailerUploadProgressRequest {
  projectId: string;
  rawMediaId: string;
  progress?: number;
  status: TrailerUploadStatusEnum;
  sourceLink?: string;
}

export interface TrailerCompleteMultipartUploadRequest {
  bucket: string;
  filePath: string;
  uploadId: string;
  rawMediaId: string;
  parts: Array<{ ETag: string; PartNumber: number }>;
}

export interface CreateTrailerUploadUrlRequest {
  projectId: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
}

export interface CreateTrailerUploadUrlResponse {
  rawMediaId: string;
  uploadId?: string;
  uploadUrl: string;
  partUrls?: Array<{ partNumber: number; uploadUrl: string }>;
  viewUrl: string;
  bucket?: string;
  filePath?: string;
}
