import { Prop, Schema } from '@nestjs/mongoose';
import { Types } from 'mongoose';

import { BaseModel } from '@app/common/entities/base.entity';

export interface TrailerRecommendations {
  bestAutoGenerated?: string;
  bestForMarketing?: string;
  bestForSocialMedia?: string;
  editorNotes?: string;
  mostUnique?: string;
}

export interface TrailerContentMetadata {
  genre?: string;
  language?: string;
  targetDuration?: number;
  title?: string;
}

@Schema({ timestamps: true })
export class TrailerProject extends BaseModel<Types.ObjectId> {
  @Prop({ type: Date })
  completedAt?: Date;

  @Prop({ type: Object })
  contentMetadata?: TrailerContentMetadata;

  @Prop({ type: String })
  contentSlug?: string;

  @Prop({ type: String })
  editorGuideS3Key?: string;

  @Prop({ type: String })
  error?: string;

  @Prop({ type: String })
  narrativeJsonS3Key?: string;

  @Prop({ required: true, type: String, unique: true })
  projectId!: string;

  @Prop({ index: true, type: Types.ObjectId })
  rawMediaId?: Types.ObjectId;

  @Prop({ type: Object })
  recommendations?: TrailerRecommendations;

  @Prop({ type: String })
  sourceLink?: string;

  @Prop({ type: Date })
  startedAt?: Date;

  @Prop({ default: [], ref: 'TrailerVariant', type: [Types.ObjectId] })
  variantIds: Types.ObjectId[] = [];
}
