import { Dialect } from 'common/enums/app.enum';

export interface ContentStaticalData {
  ALL_STARTERS_COMPLETION_RATE: number;
  ALL_STARTERS_HOOK_RATE: number;
  ALL_STARTERS_WATCH_RATE: number;
  CONTENT_DIALECT: Dialect;
  CONTENT_DURATION_SEC: number;
  CONTENT_SLUG: string;
  COUNT_COMPLETERS: number;
  COUNT_HOOKED_WATCHERS: number;
  COUNT_INTENTIONAL_WATCHERS: number;
  COUNT_STARTED_WATCHING: number;
  HOOKED_WATCHERS_COMPLETION_RATE: number;
  HOOKED_WATCHERS_WATCH_RATE: number;
  INTENTIONAL_WATCH_RATE: number;
  INTENTIONAL_WATCHERS_COMPLETION_RATE: number;
  INTENTIONAL_WATCHERS_HOOK_RATE: number;
  INTENTIONAL_WATCHERS_WATCH_RATE: number;
}
