import {
  MediaStatusEnum,
  TrailerStatusEnum,
  TrailerStatusTypeEnum,
} from 'common/entities/raw-media.entity';

// Request DTOs
export interface TrailerUploadProgressRequestDto {
  progress?: number;
  projectId: string;
  rawMediaId: string;
  sourceLink?: string;
  status:
    | MediaStatusEnum.UPLOADING
    | MediaStatusEnum.UPLOAD_COMPLETED
    | MediaStatusEnum.UPLOAD_FAILED;
}

export interface TrailerCompleteMultipartUploadRequestDto {
  bucket: string;
  filePath: string;
  parts: { ETag: string; PartNumber: number }[];
  rawMediaId: string;
  uploadId: string;
}

export interface GenerateTrailerRequestDto {
  contentMetadata?: {
    title?: string;
    genre?: string;
    language?: string;
  };
  narrativeStyles?: string[];
  projectId?: string;
  rawMediaId: string;
  targetDuration?: number;
}

export interface CreateTrailerProjectRequestDto {
  contentMetadata?: {
    title?: string;
    genre?: string;
    language?: string;
    targetDuration?: number;
  };
  contentSlug?: string;
  projectId: string;
  rawMediaId?: string;
}

// S3 trailer output from Python (snake_case)
export interface TrailerS3Output {
  s3_key: string;
  s3_uri?: string;
  s3_url?: string;
  style: string;
  variant_id: string;
}

// Local trailer output from Python (camelCase)
export interface TrailerLocalOutput {
  path: string;
  s3Url?: string;
  style: string;
  variantId: string;
}

// Output files structure from Python
export interface TrailerOutputFiles {
  jsonReport?: string;
  markdownReport?: string;
  trailerVideos?: TrailerLocalOutput[];
}

// Outputs structure from Python
export interface TrailerOutputs {
  outputFiles?: TrailerOutputFiles;
  s3Outputs?: {
    editor_guide?: { s3_key: string };
    narrative_json?: { s3_key: string };
    trailers?: TrailerS3Output[];
  };
}

// Details structure from Python completion payload
export interface TrailerProgressDetails {
  dialectDetected?: string | null;
  outputDir?: string;
  outputs?: TrailerOutputs;
  projectId?: string;
  totalTimeSeconds?: number;
  trailersCreated?: number;
  variantsGenerated?: number;
}

// Progress Event (from Python service webhook)
export interface TrailerProgressEvent {
  details?: TrailerProgressDetails;
  error?: string;
  message?: string;
  progress?: number;
  progressPercentage?: number;
  progressType?: TrailerStatusTypeEnum;
  recommendations?: {
    bestAutoGenerated?: string;
    bestForMarketing?: string;
    bestForSocialMedia?: string;
    editorNotes?: string;
    mostUnique?: string;
  };
  status: TrailerStatusEnum;
  statusType?: TrailerStatusTypeEnum;
}

// Alias for backwards compatibility
export type TrailerVariantFromPython = TrailerS3Output;

// Variant metadata from narrative JSON
export interface TrailerVariantMetadataDto {
  actual_duration?: number;
  character_intro_present?: boolean;
  closing_tag?: string;
  hook_ending_present?: boolean;
  music_recommendation?: {
    has_dialogue_gaps?: boolean;
    style?: string;
  };
  opening_hook?: string;
  production_ready?: boolean;
  shot_sequence?: {
    audio_recommendation?: string;
    dialogue_line?: string | null;
    is_hook_ending?: boolean;
    order: number;
    purpose?: string;
    recommended_duration?: number;
    scene_ref?: string;
    timecode_end?: string;
    timecode_start?: string;
    transition_in?: string;
  }[];
  structure?: {
    cliffhanger?: string;
    description?: string;
    hook_strength?: number;
    phases?: string[];
  };
  suspense_peak?: number;
  target_duration?: number;
}

// Simplified variant DTO for API responses
export interface TrailerVariantDto {
  confidence?: number;
  duration?: number;
  fileSize?: number;
  id: string;
  metadata?: TrailerVariantMetadataDto;
  s3Key: string;
  signedUrl?: string;
  style: string;
  title?: string;
}

// Response DTOs
export interface TrailerStatusResponseDto {
  error?: string;
  progress: number;
  projectId: string;
  rawMediaId: string;
  status: TrailerStatusEnum;
  statusType: TrailerStatusTypeEnum;
}

export interface GenerateTrailerResponseDto {
  message: string;
  projectId: string;
  rawMediaId: string;
  status: TrailerStatusEnum;
  statusType: TrailerStatusTypeEnum;
}

export interface CreateTrailerProjectResponseDto {
  contentMetadata?: {
    title?: string;
    genre?: string;
    language?: string;
    targetDuration?: number;
  };
  contentSlug?: string;
  projectId: string;
  rawMediaId?: string;
  startedAt?: Date;
}

// For getting project details (callable from other services)
export interface TrailerProjectDetailDto {
  completedAt?: Date;
  contentMetadata?: {
    title?: string;
    genre?: string;
    language?: string;
    targetDuration?: number;
  };
  contentSlug?: string;
  editorGuideUrl?: string;
  error?: string;
  narrativeJsonUrl?: string;
  projectId: string;
  rawMediaId?: string;
  recommendations?: {
    bestForMarketing?: string;
    bestForSocialMedia?: string;
    mostUnique?: string;
    bestAutoGenerated?: string;
    editorNotes?: string;
  };
  sourceLink?: string;
  startedAt?: Date;
  variants: TrailerVariantDto[];
}

// Query DTOs
export interface GetAllTrailerProjectsQueryDto {
  contentSlug?: string;
  page?: number;
  perPage?: number;
  search?: string;
  sortOrder?: 'asc' | 'desc';
  status?: TrailerStatusEnum;
}

// List item response DTO
export interface TrailerProjectListItemDto {
  progress?: number;
  projectId: string;
}

// Upload URL Request/Response DTOs
export interface CreateTrailerUploadUrlRequestDto {
  fileName: string;
  fileSize: number;
  mimeType: string;
  projectId: string;
}

export interface CreateTrailerUploadUrlResponseDto {
  partUrls: { partNumber: number; uploadUrl: string }[];
  rawMediaId: string;
  uploadId: string;
  uploadUrl: string;
  viewUrl: string;
  bucket: string;
  filePath: string;
}

// Task Execution Message (sent to Python service)
export interface TrailerNarrativeTaskMessage {
  workflowMode?: 'draft-narrative' | 'standard'; // NEW: Workflow mode
  approvedNarrative?: any; // NEW: Approved narrative from Phase 1
  contentMetadata?: {
    title?: string;
    genre?: string;
    language?: string;
    targetDuration?: number;
  };
  narrativeStyles?: string[];
  outputOptions: {
    generateTrailerVideos: boolean;
    trailerFormat: string;
    trailerResolution: string;
    outputS3Bucket: string;
  };
  progressBaseUrl: string;
  projectId: string;
  s3Bucket: string;
  s3FileKey: string;
  s3Region: string;
  s3TrailerFolderKey: string;
  token: string;
}
