import { PaywallItemTypeEnum } from 'common/entities/paywall.entity';
import { Dialect, Lang } from 'common/enums/app.enum';

export const validPaywallRequest = {
  [Lang.EN]: {
    name: 'Test Paywall',
    peripheralImageUrl: 'https://example.com/peripheral-image.jpg',
    renewalImage: 'https://example.com/renewal-image.jpg',
    sections: [
      {
        backgroundColor: '#007bff',
        color: '#ffffff',
        fontSize: 16,
        fontWeight: 600,
        isEnabled: true,
        label: 'Subscribe Now',
        order: 1,
        outlineColor: '#007bff',
        textColor: '#ffffff',
        type: PaywallItemTypeEnum.BUTTON,
      },
      {
        aspectRatio: '16:9',
        backgroundColor: '#f8f9fa',
        isEnabled: true,
        order: 2,
        sourceLink: 'https://example.com/paywall-image.jpg',
        type: PaywallItemTypeEnum.MEDIA_IMAGE,
      },
      {
        aspectRatio: '16:9',
        autoplay: true,
        isEnabled: true,
        loop: true,
        muted: true,
        order: 3,
        showControls: true,
        sourceLink: 'https://example.com/paywall-video.mp4',
        type: PaywallItemTypeEnum.MEDIA_VIDEO,
      },
      {
        isEnabled: true,
        order: 4,
        text: 'Welcome to our premium service!',
        type: PaywallItemTypeEnum.TEXT,
      },
    ],
  },
  [Lang.HIN]: {
    name: 'Test Paywall Hindi',
    peripheralImageUrl: 'https://example.com/peripheral-image-hin.jpg',
    renewalImage: 'https://example.com/renewal-image-hin.jpg',
    sections: [
      {
        backgroundColor: '#007bff',
        color: '#ffffff',
        fontSize: 16,
        fontWeight: 600,
        isEnabled: true,
        label: 'Subscribe Now Hindi',
        order: 1,
        outlineColor: '#007bff',
        textColor: '#ffffff',
        type: PaywallItemTypeEnum.BUTTON,
      },
      {
        aspectRatio: '16:9',
        backgroundColor: '#f8f9fa',
        isEnabled: true,
        order: 2,
        sourceLink: 'https://example.com/paywall-image-hin.jpg',
        type: PaywallItemTypeEnum.MEDIA_IMAGE,
      },
      {
        aspectRatio: '16:9',
        autoplay: true,
        isEnabled: true,
        loop: true,
        muted: true,
        order: 3,
        showControls: true,
        sourceLink: 'https://example.com/paywall-video-hin.mp4',
        type: PaywallItemTypeEnum.MEDIA_VIDEO,
      },
      {
        isEnabled: true,
        order: 4,
        text: 'Welcome to our premium service in Hindi!',
        type: PaywallItemTypeEnum.TEXT,
      },
    ],
  },
  planId: 'test_plan_001',
  targetDialects: [Dialect.HAR, Dialect.BHO],
};

export const updatedPaywallRequest = {
  [Lang.EN]: {
    name: 'Test Paywall',
    peripheralImageUrl: 'https://example.com/peripheral-image-updated.jpg',
    renewalImage: 'https://example.com/renewal-image-updated.jpg',
    sections: [
      {
        backgroundColor: '#28a745',
        color: '#ffffff',
        fontSize: 18,
        fontWeight: 700,
        isEnabled: true,
        label: 'Get Premium',
        order: 1,
        outlineColor: '#28a745',
        textColor: '#ffffff',
        type: PaywallItemTypeEnum.BUTTON,
      },
      {
        aspectRatio: '16:9',
        backgroundColor: '#f8f9fa',
        isEnabled: true,
        order: 2,
        sourceLink: 'https://example.com/updated-paywall-image.jpg',
        type: PaywallItemTypeEnum.MEDIA_IMAGE,
      },
      {
        aspectRatio: '16:9',
        autoplay: true,
        isEnabled: true,
        loop: true,
        muted: true,
        order: 3,
        showControls: true,
        sourceLink: 'https://example.com/updated-paywall-video.mp4',
        type: PaywallItemTypeEnum.MEDIA_VIDEO,
      },
    ],
  },
  [Lang.HIN]: {
    name: 'Test Paywall Hindi Updated',
    peripheralImageUrl: 'https://example.com/peripheral-image-updated-hin.jpg',
    renewalImage: 'https://example.com/renewal-image-updated-hin.jpg',
    sections: [
      {
        backgroundColor: '#28a745',
        color: '#ffffff',
        fontSize: 18,
        fontWeight: 700,
        isEnabled: true,
        label: 'Get Premium Hindi',
        order: 1,
        outlineColor: '#28a745',
        textColor: '#ffffff',
        type: PaywallItemTypeEnum.BUTTON,
      },
      {
        aspectRatio: '16:9',
        backgroundColor: '#f8f9fa',
        isEnabled: true,
        order: 2,
        sourceLink: 'https://example.com/updated-paywall-image-hin.jpg',
        type: PaywallItemTypeEnum.MEDIA_IMAGE,
      },
      {
        aspectRatio: '16:9',
        autoplay: true,
        isEnabled: true,
        loop: true,
        muted: true,
        order: 3,
        showControls: true,
        sourceLink: 'https://example.com/updated-paywall-video-hin.mp4',
        type: PaywallItemTypeEnum.MEDIA_VIDEO,
      },
    ],
  },
  planId: 'test_plan_001',
  targetDialects: [Dialect.HAR],
};

export const invalidPaywallRequest = {
  [Lang.EN]: {
    name: '',
    peripheralImageUrl: 'https://example.com/invalid-image.jpg',
    renewalImage: 'https://example.com/invalid-image.jpg',
    sections: [],
  },
  [Lang.HIN]: {
    name: '',
    peripheralImageUrl: 'https://example.com/invalid-image-hin.jpg',
    renewalImage: 'https://example.com/invalid-image-hin.jpg',
    sections: [],
  },
  planId: 'test_plan_001',
  targetDialects: [],
};

export const unauthorizedPaywallRequest = {
  [Lang.EN]: {
    name: 'Unauthorized Paywall',
    peripheralImageUrl: 'https://example.com/unauthorized-image.jpg',
    renewalImage: 'https://example.com/unauthorized-image.jpg',
    sections: [],
  },
  [Lang.HIN]: {
    name: 'Unauthorized Paywall Hindi',
    peripheralImageUrl: 'https://example.com/unauthorized-image-hin.jpg',
    renewalImage: 'https://example.com/unauthorized-image-hin.jpg',
    sections: [],
  },
  planId: 'test_plan_001',
  targetDialects: [Dialect.HAR],
};
